create table if not exists public.publicacoes_djen (
  id bigint generated by default as identity primary key,
  fonte_id text not null unique,
  hash text,
  numero_comunicacao bigint,
  numero_processo text,
  sigla_tribunal text,
  nome_orgao text,
  autor text,
  reu text,
  tipo_comunicacao text,
  tipo_documento text,
  meio text,
  texto text not null default '',
  resumo text,
  descricao_sugerida text,
  link text,
  data_disponibilizacao date not null,
  data_publicacao_preliminar date,
  prazo_dias integer check (prazo_dias is null or prazo_dias > 0),
  data_vencimento_preliminar date,
  classificacao text not null check (classificacao in ('prazo_expresso', 'possivel_prazo')),
  status text not null default 'pendente' check (status in ('pendente', 'confirmado', 'descartado')),
  oab_encontrada text,
  destinatarios jsonb not null default '[]'::jsonb,
  dados_origem jsonb not null default '{}'::jsonb,
  revisado_por uuid references auth.users(id) on delete set null,
  revisado_em timestamptz,
  confirmado_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists publicacoes_djen_status_idx
  on public.publicacoes_djen (status, data_disponibilizacao desc);

create index if not exists publicacoes_djen_processo_idx
  on public.publicacoes_djen (numero_processo);

create or replace function public.atualizar_timestamp_publicacoes_djen()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists publicacoes_djen_atualizado_em on public.publicacoes_djen;
create trigger publicacoes_djen_atualizado_em
before update on public.publicacoes_djen
for each row execute function public.atualizar_timestamp_publicacoes_djen();

alter table public.publicacoes_djen enable row level security;

drop policy if exists "Equipe autenticada consulta publicacoes DJEN" on public.publicacoes_djen;
create policy "Equipe autenticada consulta publicacoes DJEN"
on public.publicacoes_djen
for select
to authenticated
using (true);

drop policy if exists "Equipe autenticada revisa publicacoes DJEN" on public.publicacoes_djen;
create policy "Equipe autenticada revisa publicacoes DJEN"
on public.publicacoes_djen
for update
to authenticated
using (true)
with check (
  status in ('pendente', 'confirmado', 'descartado')
  and (revisado_por is null or revisado_por = auth.uid())
);

grant select on public.publicacoes_djen to authenticated;
revoke insert, update, delete on public.publicacoes_djen from anon, authenticated;
grant update (status, revisado_por, revisado_em, confirmado_em)
  on public.publicacoes_djen to authenticated;

alter publication supabase_realtime add table public.publicacoes_djen;

comment on table public.publicacoes_djen is
  'Comunicações do DJEN classificadas como prazo expresso ou possível prazo, sempre sujeitas à revisão humana.';

comment on column public.publicacoes_djen.data_publicacao_preliminar is
  'Primeiro dia útil nacional estimado após a disponibilização. Exige conferência do calendário do tribunal.';

comment on column public.publicacoes_djen.data_vencimento_preliminar is
  'Cálculo preliminar em dias úteis nacionais. Não substitui conferência profissional.';
